version: "3.3"
services:
  db:
    image: mongo
    volumes:
    - "mongo_data:/data/db"
    ports:
      - 27017:27017

  writer-api:
    build:
      context: .
      dockerfile: ./writer/Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - db
    volumes:
      - ./:/writer

  fetcher-api:
    build:
      context: .
      dockerfile: ./fetcher/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - writer-api
    volumes:
      - ./:/fetcher

volumes:
  mongo_data: